{{- if .Values.enableWorkers }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: {{ .Release.Name }}-worker
{{ include "chart_labels" . | indent 4 }}
  name: {{ .Release.Name }}-worker
  namespace: {{ .Release.Namespace }}
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.worker.metricsPort }}"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - env:
            - name: GPUSTACK_SERVER_URL
              value: http://server.{{ .Release.Namespace }}.svc:{{ .Values.server.apiPort }}
            - name: GPUSTACK_WORKER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: GPUSTACK_RUNTIME_DEPLOY
              value: "Kubernetes"
            - name: GPUSTACK_RUNTIME_DEPLOY_MIRRORED_DEPLOYMENT
              value: "true"
            - name: GPUSTACK_RUNTIME_DEPLOY_MIRRORED_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GPUSTACK_RUNTIME_KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GPUSTACK_RUNTIME_KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: GPUSTACK_WORKER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - secretRef:
                name: registration-token
                optional: false
            - configMapRef:
                name: worker-config
                optional: true
          image: {{ include "gpustack.image" . }}:{{ include "gpustack.imageTag" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Release.Name }}-worker
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            capabilities: {}
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: gpustack-data-dir
              mountPath: /var/lib/gpustack
            {{- if eq .Values.worker.runtimeClassName "ascend" }}
            #
            # (Optional) Mount Ascend driver and toolkit directories if using Ascend devices
            #
            - name: gpustack-ascend-driver
              mountPath: /usr/local/Ascend/driver
            - name: gpustack-ascend-toolkit
              mountPath: /usr/local/Ascend/ascend-toolkit
            {{- end }}
          ports:
            - name: api
              containerPort: 10150
              protocol: TCP
            - name: metrics
              containerPort: 10151
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: api
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: api
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
            successThreshold: 1
      volumes:
        - name: gpustack-data-dir
          hostPath:
            path: {{ .Values.defaultDataDir }}
            type: DirectoryOrCreate
        {{- if eq .Values.worker.runtimeClassName "ascend" }}
        #
        # (Optional) Mount Ascend driver and toolkit directories if using Ascend devices
        #
        - name: gpustack-ascend-driver
          hostPath:
            path: /usr/local/Ascend/driver
            type: DirectoryOrCreate
        - name: gpustack-ascend-toolkit
          hostPath:
            path: /usr/local/Ascend/ascend-toolkit
            type: DirectoryOrCreate
        {{- end }}
      hostNetwork: true
      hostIPC: true
      serviceAccountName: {{ .Release.Name }}-worker
      dnsPolicy: ClusterFirstWithHostNet
      {{- if .Values.worker.runtimeClassName }}
      runtimeClassName: {{ .Values.worker.runtimeClassName }}
      {{- end }}
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
{{- end }}
