version: "3.8"
name: gpustack-observability-stack

services:
  gpustack-server:
    image: gpustack/gpustack
    container_name: gpustack-server
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - gpustack-data:/var/lib/gpustack
      - /var/run/docker.sock:/var/run/docker.sock
    runtime: nvidia

  prometheus:
    image: prom/prometheus
    container_name: gpustack-prometheus
    restart: unless-stopped
    network_mode: host
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: gpustack-grafana
    restart: unless-stopped
    network_mode: host
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles
    volumes:
      - ./grafana/grafana_provisioning:/etc/grafana/provisioning:ro
      - ./grafana/grafana_dashboards:/etc/dashboards:ro



volumes:
  prom_data: {}
  gpustack-data: {}
