apiVersion: v2
name: gpustack-higress-plugins
description: A Helm chart for deploying GPUStack Higress WasmPlugins
version: 0.1.0
appVersion: "2.0.2"
keywords:
  - higress
  - wasm
  - plugin
  - gpustack
home: https://github.com/gpustack/gpustack
sources:
  - https://github.com/gpustack/gpustack
icon: https://docs.gpustack.ai/2.0/assets/logo.png
kubeVersion: ">=1.30.0-0"
annotations:
  artifacthub.io/links: |
    - name: GitHub
      url: https://github.com/gpustack/gpustack
